import = ["~/.config/alacritty/rose-pine.toml"]

font.normal = { family = "Fira Code Nerd Font", style="Medium,Regular"}
# font
# font_family      Fira Code Nerd Font 
# bold_font        auto
# italic_font      auto
# bold_italic_font auto
#
#
